/**
 * SPDX-License-Identifier: GPL-2.0-only
 * Copyright (C) 2025 Bardia Moshiri <bardia@furilabs.com>
 */

#ifndef INTROSPECT_H
#define INTROSPECT_H

static const gchar biomd_introspection_xml[] =
  "<node>"
  "  <interface name='io.FuriOS.Biomd'>"
  "    <method name='GetSupportedModules'>"
  "      <arg type='as' name='modules' direction='out'/>"
  "    </method>"
  "    <method name='Ping'>"
  "      <arg type='b' name='result' direction='out'/>"
  "    </method>"
  "  </interface>"
  "</node>";

static const gchar fingerprint_introspection_xml[] =
  "<node>"
  "  <interface name='io.FuriOS.Biomd.Fingerprint'>"
  "    <method name='Enroll'>"
  "      <arg type='s' name='finger_name' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='Identify'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='StopEnroll'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='StopIdentify'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='RemoveFinger'>"
  "      <arg type='s' name='finger_name' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='RenameFinger'>"
  "      <arg type='s' name='old_name' direction='in'/>"
  "      <arg type='s' name='new_name' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='GetFingerEnrollmentDate'>"
  "      <arg type='s' name='finger_name' direction='in'/>"
  "      <arg type='x' name='enrollment_date' direction='out'/>"
  "    </method>"
  "    <property name='State' type='i' access='read'/>"
  "    <property name='EnrollmentProgress' type='i' access='read'/>"
  "    <property name='EnrolledFingers' type='as' access='read'/>"
  "    <property name='ErrorInfo' type='i' access='read'/>"
  "    <property name='AcquisitionInfo' type='i' access='read'/>"
  "    <property name='HardwareAvailable' type='b' access='read'/>"
  "    <property name='ValidFingerNames' type='as' access='read'/>"
  "    <signal name='StateChanged'>"
  "      <arg type='i' name='state'/>"
  "    </signal>"
  "    <signal name='EnrollmentProgressChanged'>"
  "      <arg type='i' name='progress'/>"
  "    </signal>"
  "    <signal name='EnrolledFingersChanged'>"
  "      <arg type='as' name='fingers'/>"
  "    </signal>"
  "    <signal name='ErrorInfoChanged'>"
  "      <arg type='i' name='error'/>"
  "    </signal>"
  "    <signal name='AcquisitionInfoChanged'>"
  "      <arg type='i' name='info'/>"
  "    </signal>"
  "    <signal name='Identified'>"
  "      <arg type='s' name='finger_name'/>"
  "    </signal>"
  "  </interface>"
  "</node>";

static const gchar face_introspection_xml[] =
  "<node>"
  "  <interface name='io.FuriOS.Biomd.Face'>"
  "    <method name='RegisterEnrollmentAgent'>"
  "      <arg type='o' name='agent_path' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='UnregisterEnrollmentAgent'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='RegisterRecognitionAgent'>"
  "      <arg type='o' name='agent_path' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='UnregisterRecognitionAgent'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='CreateAgent'>"
  "      <arg type='o' name='agent_path' direction='out'/>"
  "    </method>"
  "    <method name='DestroyAgent'>"
  "      <arg type='o' name='agent_path' direction='in'/>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <property name='State' type='i' access='read'/>"
  "    <property name='FaceEnrolled' type='b' access='read'/>"
  "    <property name='ImplementationType' type='i' access='read'/>"
  "    <signal name='StateChanged'>"
  "      <arg type='i' name='state'/>"
  "    </signal>"
  "    <signal name='FaceEnrolledChanged'>"
  "      <arg type='b' name='enrolled'/>"
  "    </signal>"
  "  </interface>"
  "</node>";

static const gchar face_agent_introspection_xml[] =
  "<node>"
  "  <interface name='io.FuriOS.Biomd.Face.Agent'>"
  "    <method name='StartEnrollment'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='StartRecognition'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='Cancel'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='RemoveFaceData'>"
  "      <arg type='b' name='success' direction='out'/>"
  "    </method>"
  "    <method name='SubmitFrame'>"
  "      <arg type='h' name='memfd' direction='in'/>"
  "      <arg type='i' name='width' direction='in'/>"
  "      <arg type='i' name='height' direction='in'/>"
  "      <arg type='i' name='channels' direction='in'/>"
  "      <arg type='u' name='format' direction='in'/>"
  "      <arg type='b' name='accepted' direction='out'/>"
  "    </method>"
  "    <property name='Busy' type='b' access='read'/>"
  "    <property name='HasAccess' type='b' access='read'/>"
  "    <property name='LastEnrollmentState' type='u' access='read'/>"
  "    <property name='LastRecognitionState' type='u' access='read'/>"
  "    <property name='EnrollmentProgress' type='i' access='read'/>"
  "    <property name='Mode' type='i' access='read'/>"
  "    <signal name='AccessChanged'>"
  "      <arg type='b' name='has_access'/>"
  "    </signal>"
  "    <signal name='EnrollmentStateChanged'>"
  "      <arg type='u' name='state'/>"
  "    </signal>"
  "    <signal name='EnrollmentProgressChanged'>"
  "      <arg type='i' name='progress'/>"
  "    </signal>"
  "    <signal name='RecognitionStateChanged'>"
  "      <arg type='u' name='state'/>"
  "    </signal>"
  "  </interface>"
  "</node>";

#endif /* INTROSPECT_H */
